### ISSUE TITLE
Persona MC2

### ISSUE THREAD

**Issue by zedpr0** [xeon1989/QDLink-Unlocked#1]
How to install file explorer to open the apk in the ihu of persona mc2? can we use the [Proton-X50-APK-Installer-ATLAS](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS) script with the persona MC2? Thanks.

**Comment by xeon1989** [comment]
Hi, unfortunately the script doesn't work on Persona.

**Comment by zedpr0** [comment]
Thats sucks, thanks anyway, is there anything we can do for the persona? or just wait and hope someone cracks it?

**Comment by xeon1989** [comment]
What's the firmware version of IHU of your Persona MC2?

**Comment by zedpr0** [comment]
According to the software update screen it is SWPERSON0227H1539.00163

**Comment by xeon1989** [comment]
have u tried this?

https://tinyurl.com/2ctdty3n

**Comment by zedpr0** [comment]
Thank you so much, I tired the guide stuck at package installer keeps stopping. Is it a problem with the apks? none of them including yours can be installed.

**Comment by xeon1989** [comment]
Unfortunately I do not have the knowledge to further advice you.
Please try to ask in public community such as Persona MC2 Facebook group.

**Comment by zedpr0** [comment]
No worries mate, thank you so much for your help so far. Have a wonderful evening.
